Add Holyiot nrf52840
adafruit/Adafruit_nRF52_Bootloader pull request #173
Opened 2020-10-26 22:42 UTC by Edrig

2020-10-26 23:10 UTC, ladyada requested changes

2020-10-26 23:10 UTC, ladyada commented on src/boards/holyiot_nrf52840/board.h
> +#define USB_DESC_VID           0x239A
hi you cannot use adafruit VID/PID for this non-adafruit product

2020-10-27 08:33 UTC, Edrig commented
Hello, this is for use à  breakout for the Holyiot module, but available in open source [](). What VID / PID can we use in this case ?

2020-10-27 12:52 UTC, dhalbert commented
You might first ask Holyiot. They already sell USB devices, and could allocate you one. Another alternative is https://github.com/pidcodes/pidcodes.github.com.

2020-10-27 23:54 UTC, Edrig commented
hello im using the vid/pid 
that I was assigned following my request here :

https://github.com/adafruit/circuitpython/issues/2786

Thank you

2020-10-28 14:47 UTC, ladyada commented
oh that was a long time ago! ok thanks!

2020-10-28 14:47 UTC, ladyada approved these changes

2020-10-29 03:18 UTC, merged