add 833 support for v7
adafruit/Adafruit_nRF52_Bootloader pull request #231
Opened 2021-11-13 23:42 UTC by kbladewht

2021-11-15 04:54 UTC, hathach requested changes
Thank you for the PR. It looks OK, however, per USB specs, we must enforce an unique vid/pid for each board. The vid/pid cannot be re-used. You need to apply for 1 from donor as mentioned in below reviews.

2021-11-15 04:54 UTC, hathach commented on src/boards/keystar/board.h
> +#define USB_DESC_CDC_ONLY_PID  0x0029
The PID is already used by Feather nRF52840, each board must have its unique vid/pid. If you don't have one, try to apply for one https://pid.codes/

2021-11-15 04:54 UTC, hathach commented on src/boards/nrf52833/board.h
> +#define UF2_VOLUME_LABEL   "KSTARORION833"
same as above, each board must have unique vid/pid

2021-11-15 04:54 UTC, hathach commented on src/boards/nrf52833/board.h
> +/*
which board is this nrf52833, it is to generic, maybe adding an manufacturer name to distinguish it from other 833 boards.

2021-12-02 22:07 UTC, jpconstantineau commented
@kbladewht Do you think you will be able to work on this? 
When referring to #246, your work would benefit all nRF52833 users and the community would really appreciate if the new board you have could be split from this PR and the work you mention in the title of the PR (support for SD V7) be merged in.  I suspect that the blocker is indeed that USB VID/PID. Splitting this PR in two would remove the blocker for merging the core of this effort. 

Thanks

2021-12-09 06:02 UTC, hathach commented
@jpconstantineau OP seems to be busy atm, if you need this asap, you could check out OP's branch, make update yourself then submit it as PR. Make sure the commmit log is as it is that will give credit to OP. When your PR is merged, github is smart enough to set this PR status to merge as well.

2021-12-09 19:26 UTC, jpconstantineau commented
@hathach Thanks for the comments.  I have been busy looking at the circuitpython nrf52833 issues and am close to move towards this.  Good to know that github is clever enough to close two PRs if one is the continuation of the other.

2021-12-22 05:45 UTC, closed without merging