Add New Board: Raytac MDBT50Q Demo Board 40
adafruit/Adafruit_nRF52_Bootloader pull request #233
Opened 2021-11-25 12:44 UTC by markbirss

* adding Raytac MDBT50Q Demo Board 40 files

2021-11-25 15:07 UTC, hathach requested changes
VID/PID must be uniquely assigned. check out review comment for detail

2021-11-25 15:07 UTC, hathach commented on src/boards/raytac_mdbt50q_db_40/board.h
> +#define USB_DESC_CDC_ONLY_PID  0x010C
it is required by this repo that each board must have its own unique VID/PID. I double check, but this PID isn't assigned by Adafruit to any boards yet. Please try to get one from PID donor.

2021-11-26 07:18 UTC, markbirss commented
Ok, i understand your comment, but what is "PID donor" ?

2021-11-26 07:20 UTC, hathach commented
> Ok, i understand your comment, but what is "PID donor" ?

I mean you could ask from one of the manufacturer to get an PID assigned to this board.

2021-11-26 07:24 UTC, markbirss commented
Ok, will ask Raytac about it

2021-11-26 07:26 UTC, markbirss commented
The device was loaded with this when i reeived it
ID 1915:521a Nordic Semiconductor ASA nRF52 USB CDC BLE Demo

2021-11-26 07:41 UTC, markbirss commented
@hathach  Ok, i just found this github issue about the same thing for circuitpython for the same device

https://github.com/adafruit/circuitpython/issues/3128#issuecomment-655077754

This suggests I must use 

PID 0x00BB  # bootloader ?

2021-11-26 08:14 UTC, hathach commented
@markbirss it is the same board, so yes, we should/must use that PID. Please update your PR

2021-11-26 08:40 UTC, markbirss commented
> 0x00BB

Sure, i have made the required change

2021-11-26 11:22 UTC, hathach requested changes
board-id is not correct, it must follow uf2 convention.

2021-11-26 11:47 UTC, markbirss commented on src/boards/raytac_mdbt50q_db_40/board.h
> +#define UF2_BOARD_ID            "RAYTAC-MDBT50Q-DB-40"
@hathach 
Im not sure I understand your comment ?

Looking at the other already defined Raytec Board, what is the board-id you referring to ?

https://github.com/adafruit/Adafruit_nRF52_Bootloader/blob/master/src/boards/raytac_mdbt50q_rx/board.h
```
//------------- UF2 -------------//
#define UF2_PRODUCT_NAME        "Raytac MDBT50Q-RX"
#define UF2_VOLUME_LABEL        "MDBT50QBOOT"
#define UF2_BOARD_ID            "nRF52840-MDBT50Q_RX-verD"
#define UF2_INDEX_URL           "https://www.adafruit.com/product/5199"
```

2021-11-30 05:55 UTC, hathach commented on src/boards/raytac_mdbt50q_db_40/board.h
> +#define UF2_BOARD_ID            "RAYTAC-MDBT50Q-DB-40"
board-id must follow format dictate by uf2 spec https://github.com/microsoft/uf2#files-exposed-by-bootloaders

2021-11-30 07:15 UTC, markbirss commented on src/boards/raytac_mdbt50q_db_40/board.h
> +#define UF2_BOARD_ID            "RAYTAC-MDBT50Q-DB-40"
@hathach  Ok, for your review, made changes to UF2_BOARD_ID

2021-11-30 08:54 UTC, hathach reviewed
everything look good, only one last thing: you need add the board to ci list so that its binaries is generated when released https://github.com/adafruit/Adafruit_nRF52_Bootloader/blob/master/.github/workflows/githubci.yml

2021-11-30 09:12 UTC, markbirss commented
@hathach  Ok, here is the PR for that
https://github.com/adafruit/Adafruit_nRF52_Bootloader/pull/245

2021-11-30 09:27 UTC, hathach approved these changes

2021-11-30 09:28 UTC, merged