Add support for XIAO BLE Sense boards
adafruit/Adafruit_nRF52_Bootloader pull request #291
Opened 2023-01-27 01:44 UTC by aovestdipaperino

Added support for Xiao BLE nrf52840 boards.
IDs are taken from here: https://github.com/0hotpotman0/Adafruit_nRF52_Bootloader

Changes: 
* number of LEDs is set to 1, because a larger number causes OTA issues ¯\_(ツ)_/¯
* Set the proper SD version in the .mk files, again to fix OTA issues due to mismatched version.

2023-01-30 02:15 UTC, hathach requested changes
please correct the BOARD_ID and also add these new boards to the ci as well https://github.com/adafruit/Adafruit_nRF52_Bootloader/blob/master/.github/workflows/githubci.yml#L17

2023-01-30 02:15 UTC, hathach commented on src/boards/xiao_nrf52840_ble/board.h
> +#define UF2_BOARD_ID       "Seeed_XIAO_nRF52840"
UF2_BOARD_ID must follow the uf2 specs format https://github.com/microsoft/uf2#files-exposed-by-bootloaders

2023-02-06 02:27 UTC, aovestdipaperino commented
Fixed all suggestions.

2023-02-08 02:00 UTC, hathach approved these changes
look good, thank you for your PR

2023-02-08 02:00 UTC, merged

2024-05-24 10:24 UTC, faizannazir commented
only led blinking